### ISSUE TITLE
Pbase roadmap to version 1.0.0: ensembldb integration

### ISSUE THREAD

**Issue by jotsetung** [ComputationalProteomicsUnit/Pbase#31]
### Integration of `ensembldb` (https://github.com/jotsetung/ensembldb)

In addition to `biomaRt`, use functionality from the `ensembldb` package for genomic mapping of protein/peptide features and to retrieve protein annotations.
+ [x] Fetch protein annotations (as a `Proteins` object) from `EnsDb`s.
+ [x] Map peptide features to genomic coordinates using `ensembldb`.
+ [x] Add a vignette that describes this functionality.

**Comment by jotsetung** [comment]
### Adapt `Proteins` object to resemble `GRanges`

This is matter of discussion - it contains mostly some of my suggestions thus far.
+ [ ] Allow redundant `seqnames`.
+ [ ] Link `names` to `seqnames`.

**Comment by lgatto** [comment]
Biomart has become increasingly unreliable. I can see `EnsDb` becoming the main source of data/annotation.

**Comment by sgibb** [comment]
If that is the case do we want to drop the `Biomart` support completely?

**Comment by jotsetung** [comment]
wouldn't drop `Biomart` completely right now - eventually later - also since `EnsDb` databases are not (yet) available for all species and Ensembl versions.

**Comment by lgatto** [comment]
Yes, let's see how things work out. Also, I would be curious to compare Biomart and EnsDb (i.e. using Ensembl's perl API) mappings. I they are the same, then, yes, we can drop the former. Otherwise, I would be interested in understanding where these differences come from. 

@jotsetung 
- do you query stable Ensembl releases
- is there something like *just added*/devel Ensembl annotations 
- can you query old releases

What I think would be interesting would be to create annotation packages with `ensembldb` at the beginning of a project, query these, and archive them to assure reproducibility. This is something that can't be done for Biomart. Of course, it is possible to store the `Proteins` object, but being able to regenerate them knowing that the annotation won't change is important too.

**Comment by jotsetung** [comment]
> + do you query stable Ensembl releases

Yes, I'm building an `EnsDb` object for a certain Ensembl release and species.

> + is there something like _just added_/devel Ensembl annotations 

That I don't know - I'm extracting all genes, transcripts, exons and proteins that are stored in the Ensembl MySQL database for a certain species/Ensembl release. Basically, the content should be the same than the one you get on the ensembl web site.

> + can you query old releases

You can get the MySQL database dumps for each (also historic) Ensembl release and you can checkout the Perl API code matching that release. So, yes, you can do that for all species and all releases of Ensembl (and also of Ensemblgenomes - so even more species!).

Here I'm also thinking of a better solution. Would be nice to provide `EnsDb` SQLite databases for a variety of species and for each Ensembl version through `AnnotationHub`.

One of the main reasons I started `ensembldb` was to have annotation databases easy to use from R matching certain Ensembl releases and thus guaranteeing reproducibility of analyses.

**Comment by lgatto** [comment]
@jotsetung - could send a PR to merge `ensembldb` into `master`
